[project]
name = "Smart Personeal Hub"
version = "0.1.1"
description = ""
readme = "README.md"
requires-python = ">=3.10"

authors = [
    { name = "Abdelhaq El-hafidy", email = "abdeelhap12345@gmail.com" }
]

dependencies = [
    "flet>=0.86.5",
    "cryptography>=43.0.0",
    "Pillow>=10.0.0",
    "matplotlib>=3.8.0",
    "openpyxl>=3.1.0",
    "reportlab>=4.0.0"
]

[dependency-groups]
dev = [
    "flet-cli>=0.86.5",
    "flet-desktop>=0.86.5",
    "flet-web>=0.86.5",
    "flet[test]>=0.86.5",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]

[tool.flet]
org = "com.abdeelhap12345.smart"
product = "smart-personeal"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
